---
title: "Model development"
author: "Qingqing Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  workflowr::wflow_html:
    toc: false
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(png)
library(grid)
```


## Model study area

```{r}
study_area <- readPNG(here::here("data/pic/study-area.png"))
grid.raster(study_area)
```


## Model Structure 
```{r}
structure <- readPNG(here::here("data/pic/model-structure.png"))
grid.raster(structure)
```

## Agents decision-making process

```{r}
decision_tree <- readPNG(here::here("data/pic/decision_tree.png"))
grid.raster(decision_tree)
```

## Model GUI
```{r}
gui <- readPNG(here::here("data/pic/gui.png"))
grid.raster(gui)
```


- All codes and data of the model hosted on: https://github.com/chenqingqing/draw-15minsCity-bubbles/tree/main/model

- A simple demo of the model can be found at: https://github.com/chenqingqing/draw-15minsCity-bubbles/tree/main/model/demo

