---
title: "Model experiments"
author: "Qingqing Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  workflowr::wflow_html:
    toc: false
    code_folding: show
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(here)
library(tidyverse)
library(dplyr)
library(readxl)
library(sf)
library(tmap)
```


## Scenario 1: Different Population 

### Average walking distance
```{r}
df_pop_averageDist <- read_excel(here("model/data/experiment/experiment-population-averageDist.xlsx"), sheet = "averageDist") %>% 
  mutate(Minute = round(Minute, 2))
```


```{r}
scale_factor <- 4000/250
df_pop_averageDist %>% 
  dplyr::select(-Second) %>% 
  gather(key = "Population", value = "Distance", -Minute) %>% 
  mutate(Population = factor(Population, levels = c("Pop.100", "Pop.300", "Pop.500", "Pop.700", "Pop.900", "Pop.1000"))) %>% 
  mutate(Distance = Distance * scale_factor) %>% 
  ggplot(., aes(x = Minute, y = Distance, color = Population)) +
  geom_line(size = 1) +
  geom_vline(xintercept = 15, linetype="dotted", 
                color = "blue", size=2) +
  annotate("text", x = 22, y = 1150, label = "15 Minutes") +
  scale_x_continuous(breaks = seq(0, 100, 5)) +
  scale_y_continuous(breaks = seq(0, 1800, 100)) + 
  theme_bw() +
  theme(legend.position = c(0.9, 0.3), 
        title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10)) +
  labs(y = "Distance (m)", title = "Distribution of walking distance over time by different population sizes", caption = "Distance is measured based on the average distance of all agents")
```

### Distance to the most density person

```{r}
df_pop_densityDist <- read_excel(here("model/data/experiment/experiment-population-densityDist.xlsx"), sheet = "densityDist") %>% 
  mutate(Minute = round(Minute, 2))
```


```{r}
df_pop_densityDist %>% 
  dplyr::select(-Second) %>% 
  gather(key = "Population", value = "Distance", -Minute) %>% 
  mutate(Population = factor(Population, levels = c("Pop.100", "Pop.300", "Pop.500", "Pop.700", "Pop.900", "Pop.1000"))) %>% 
  mutate(Distance = Distance * scale_factor) %>% 
  ggplot(., aes(x = Minute, y = Distance, color = Population)) +
  geom_line(size = 1) +
  geom_vline(xintercept = 15, linetype="dotted", 
                color = "blue", size=2) +
  annotate("text", x = 27, y = 800, label = "15 Minutes") +
  scale_x_continuous(breaks = seq(0, 100, 5)) +
  scale_y_continuous(breaks = seq(0, 2000, 100)) + 
  theme_bw() +
  theme(legend.position = c(0.72, 0.77), 
        title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10)) +
  labs(y = "Distance (m)", title = "Distribution of walking distance over time by different population sizes", caption = "Distance is measured based on the most density agent")
```


## Scenario 2: Different spatial distribution of POIs

```{r}
streets_with_POIs_queens2km <- read_sf(here::here("data/streets_with_POIs/streets_with_POIs_queens2km.shp"))

if(file.exists(here("data/streets_with_POIs/streets_with_POIs_queens2km_updated.shp"))){
  sf_div <- read_sf(here("data/streets_with_POIs/streets_with_POIs_queens2km_updated.shp"))
}else{
  set.seed(1234)
  div <- c(0.00, 0.05, 0.42, 0.39, 1.00, 0.88, 0.87, 0.60, 0.63, 0.76, 0.79)
  sf_div <- streets_with_POIs_queens2km %>% 
    dplyr::select(id, nrm_dvr) %>% 
    mutate(random_nrm_dvr = sample(div, nrow(.), replace = T))
  write_sf(sf_div, here::here("data/streets_with_POIs/streets_with_POIs_queens2km_updated.shp"))
}

tm_shape(sf_div %>% rename(Random.norm.Div = rndm_n_)) +
  tm_lines(col = "Random.norm.Div", 
           palette = "PuRd", 
           style = "fixed", 
           breaks = c(0, 0.05, 0.1, 0.3, 0.5, 0.7, 0.9, 1.0), 
           labels = c("Low", "", "", "Medium", "", "", "High"),
           n = 7) +
  tm_layout(legend.outside = T, 
            frame = F)

sf_div %>% 
  st_set_geometry(NULL) %>% 
  gather(key = "type", value = "value", -id) %>% 
  mutate(type = case_when(
    type == "nrm_dvr" ~ "Orginal", 
    TRUE ~ "Random"
  )) %>% 
  ggplot() +
  geom_histogram(aes(value, fill = type), position = "dodge") +
  facet_wrap(~type, scales = "free") +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Normalized diversity of POIs", y = "Count", title = "Distribution of normalized diversity of POIs")
```


```{r}
df_diversity <- read_excel(here("model/data/experiment/experiment-diversity.xlsx"), sheet = "diversity") %>% 
  mutate(Minute = round(Minute, 2))
```

```{r}
df_diversity %>% 
  dplyr::select(-Second) %>% 
  gather(key = "Situation", value = "Distance", -Minute) %>% 
  mutate(Distance = Distance * scale_factor) %>% 
  ggplot(., aes(x = Minute, y = Distance, color = Situation)) +
  geom_line(size = 1) +
  geom_vline(xintercept = 15, linetype="dotted", 
                color = "blue", size=2) +
  annotate("text", x = 23, y = 1100, label = "15 Minutes") +
  scale_x_continuous(breaks = seq(0, 100, 5)) +
  scale_y_continuous(breaks = seq(0, 1800, 100)) + 
  theme_bw() +
  theme(legend.position = c(0.9, 0.2), 
        title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10)) +
  labs(y = "Distance (m)", title = "Distribution of walking distance over time under different situations", caption = "Distance is measured based on the average distance of all agents")
```

