---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
    code_folding: hide
editor_options:
  chunk_output_type: console
---

<style>
body {text-align: justify}
</style>

## Drawing the ‘15-minute City’ Bubble: Crowd simulation to detect the size of local community-life circle in New York City

The recent uptake of  ’15-minute city’ planning ideas sought after by cities around the world (Weng et al. 2019, Pozoukidou and Chatziyiannaki 2021) refers to the idea that all residents can access most of their daily needs (e.g., groceries, work, education, shopping, health, exercise, entertainment, etc.) within 15 minutes (up to 20 minutes), commuting from their own doorsteps by walking, cycling, or public transportation. This notion has been sharply discussed lately during the Covid-19 pandemic, as the pandemic has significantly restricted human movement, forcing people to stay at home and only go out for basic needs (Dinah Lewis Boucher, 2020). Thus, ushering in a new era of integrated urban fabric which combines most of residents’ life essentials to each local community is promoted. 

However, when taking the history of urban inequity (Duncan et al. 2012, Stephens 2012) into account, challenges of implementing the concept of ‘15-minute city’ arise and the challenges could vary from different countries in different places. For instance, people who stay in New York City may be able to gain most of their daily needs within 15-minute traveling, while people who live in the small and midsized cities may require more time to get their essentials, especially where there is a lack of public transports. So, 

  - what is the exact size of a 15-minute city? 
  - How much does the size vary from diverse traveling modes (e.g., walking, cycling, or driving)? 
  - How much does the size fluctuate between different places within a city or across countries? 
  - Does the size reach a plateau before 15 minutes of traveling? 
  - If it does, does that indicates people could obtain their essentials in a shorter distance? 
  

The benchmark of quantifying a 15-minute city has not come with a consensus in the current state-of-the-art. In order to quantitatively draw the size of a 15-minute city, I spatiotemporally simulate residential movements on streets by developing an Agent-Based Model (ABM). I hope the bottom-up approach introduced in this study could help detect the flexibility of defining a ‘15-minute city’ and thereafter help investigate the underlying factors that affect its definition. The model is put to the test in application to a 4 by 4-kilometer square neighbourhood in Queens, which is located in the easternmost of New York. According to NY.gov, Queens is the largest in the area and the second-most in the population of the five boroughs of New York City, known for its diverse culture and diversified economy, and attracts people all over the world. It might be interesting to reimagine what the neighbourhood could look like in this ‘cornucopia’ as a 15-minute city model. 



```{r}
library(png)
library(grid)
study_area <- readPNG(here::here("data/pic/study-area.png"))
grid.raster(study_area)
```


### Reference
Aziz, H.M.A., Park, B.H., Morton, A., Stewart, R.N., Hilliard, M., and Maness, M., 2018. A high resolution agent-based model to support walk-bicycle infrastructure investment decisions: A case study with New York City. Transportation Research Part C: Emerging Technologies, 86, 280–299.

Badland, H., White, M., MacAulay, G., Eagleson, S., Mavoa, S., Pettit, C., and Giles-Corti, B., 2013. Using simple agent-based modeling to inform and enhance neighborhood walkability. International Journal of Health Geographics, 12 (1), 58.

Batty, M., 2012. Smart Cities, Big Data. Environment and Planning B: Planning and Design, 39 (2), 191–193.

Bettencourt, L.M.A., 2014. The Uses of Big Data in Cities. Big Data, 2 (1), 12–22.
Crooks, A., Croitoru, A., Lu, X., Wise, S., Irvine, J.M., and Stefanidis, A., 2015. Walk This Way: Improving Pedestrian Agent-Based Models through Scene Activity Analysis. ISPRS International Journal of Geo-Information, 4 (3), 1627–1656.

Duncan, D.T., Aldstadt, J., Whalen, J., White, K., Castro, M.C., and Williams, D.R., 2012. Space, race, and poverty: Spatial inequalities in walkable neighborhood amenities? Demographic research, 26 (17), 409–448.

Freudendal-Pedersen, M., 2020. Sustainable urban futures from transportation and planning to networked urban mobilities. Transportation Research Part D: Transport and Environment, 82, 102310.

Hu, S., Xiong, C., Yang, M., Younes, H., Luo, W., and Zhang, L., 2021. A big-data driven approach to analyzing and modeling human mobility trend under non-pharmaceutical interventions during COVID-19 pandemic. Transportation Research Part C: Emerging Technologies, 124, 102955.

Jacobs, A.B., 1993. Great Streets. University of California Transportation Center, Working Papers. University of California Transportation Center, No. qt3t62h1fv.

Kim, J.-S., Jin, H., Kavak, H., Rouly, O.C., Crooks, A., Pfoser, D., Wenk, C., and Züfle, A., 2020. Location-Based Social Network Data Generation Based on Patterns of Life. In: 2020 21st IEEE International Conference on Mobile Data Management (MDM). Presented at the 2020 21st IEEE International Conference on Mobile Data Management (MDM), 158–167.

Knura, M., 2019. Agent Based Simulation of Pedestrian Movement in Urban Environments, 5.
Liu, K., Murayama, Y., and Ichinose, T., 2021. Exploring the relationship between functional urban polycentricity and the regional characteristics of human mobility: A multi-view analysis in the Tokyo metropolitan area. Cities, 111, 103109.

Liu, S.B., Lo, S.M., Tsui, K.L., and Wang, W.L., 2015. Modeling Movement Direction Choice and Collision Avoidance in Agent-Based Model for Pedestrian Flow. Journal of Transportation Engineering, 141 (6), 04015001.

Meekan, M.G., Duarte, C.M., Fernández-Gracia, J., Thums, M., Sequeira, A.M.M., Harcourt, R., and Eguíluz, V.M., 2017. The Ecology of Human Mobility. Trends in Ecology & Evolution, 32 (3), 198–210.

Nowok, B., Raab, G.M., and Dibben, C., 2016. synthpop : Bespoke Creation of Synthetic Data in R. Journal of Statistical Software, 74 (11).

Object,  object, 2020. Local Living, Rise of 20 Minute Cities Post-Covid [online]. The Urban Developer. Available from: https://theurbandeveloper.com/articles/local-living-rise-of-20-minute-cities-post-covid [Accessed 20 Mar 2021].

Pozoukidou, G. and Chatziyiannaki, Z., 2021. 15-Minute City: Decomposing the New Urban Planning Eutopia. Sustainability, 13 (2), 928.

Read ‘America Becoming: Racial Trends and Their Consequences: Volume I’ at NAP.edu, n.d.

Weng, M., Ding, N., Li, J., Jin, X., Xiao, H., He, Z., and Su, S., 2019. The 15-minute walkable neighborhoods: Measurement, social inequalities and implications for building healthy communities in urban China. Journal of Transport & Health, 13, 259–273.

Where the ‘15-Minute City’ Falls Short, 2021. Bloomberg.com, 2 Mar. 

Whitworth, A., 2020. synthACS: Spatial MicroSimulation Modeling with Synthetic American Community Survey Data [online]. Available from: /paper/synthACS%3A-Spatial-MicroSimulation-Modeling-with-Whitworth/2bf10b9bd67fdc46d2372416a4f1367ff8f45832 [Accessed 22 Mar 2021].

Yang, Y., Roux, A.V.D., Auchincloss, A.H., Rodriguez, D.A., and Brown, D.G., 2011. A Spatial Agent-Based Model for the Simulation of Adults’ Daily Walking Within a City. American Journal of Preventive Medicine, 40 (3), 353–361.

Zhu, W., Nedovic-Budic, Z., Olshansky, R.B., Marti, J., Gao, Y., Park, Y., McAuley, E., and Chodzko-Zajko, W., 2013. Agent-Based Modeling of Physical Activity Behavior and Environmental Correlations: An Introduction and Illustration. Journal of Physical Activity and Health, 10 (3), 309–322.


